# Generated by Django 3.1.4 on 2021-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('questions', '0001_initial'), ('questions', '0002_auto_20201226_2213'), ('questions', '0003_auto_20201230_0048'), ('questions', '0004_auto_20201230_1716'), ('questions', '0005_auto_20201231_1423'), ('questions', '0006_question_question_release_datetime'), ('questions', '0007_auto_20210101_2339'), ('questions', '0008_auto_20210102_2027'), ('questions', '0009_auto_20210103_2211')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('short_description', models.CharField(blank=True, help_text='A short summary should suffice.', max_length=200, null=True, verbose_name='Summary of Question')),
                ('long_description', models.TextField(help_text='Write this in the Markdown language!', max_length=10000, verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('input_generation_code', models.TextField(help_text='Make sure to follow the specifications in the README.md file!', verbose_name='Input Generation Code')),
                ('question_release_datetime', models.DateTimeField(help_text='When should this question be released?', verbose_name='Question Release Date-Time')),
                ('override_key', models.CharField(help_text="If the question is inaccessible, enter the full url to the question, followed by 'OK=', followed by this key to access it.", max_length=10, verbose_name='Override Key')),
            ],
        ),
    ]
