# Generated by Django 3.1.4 on 2021-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_generation_code',
            field=models.TextField(help_text='Make sure to follow the specifications in the README.md file.', verbose_name='Input Generation Code'),
        ),
        migrations.AlterField(
            model_name='question',
            name='long_description',
            field=models.TextField(help_text='Write this in the Markdown language.', max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_release_datetime',
            field=models.DateTimeField(help_text='When should this question be released?', verbose_name='Question Release Datetime'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Summary of Question'),
        ),
    ]
