# Generated by Django 3.1.4 on 2020-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201226_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Date Published'),
        ),
    ]
