# Generated by Django 3.1.4 on 2021-01-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210118_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='override_key',
        ),
    ]
