# Generated by Django 3.1.4 on 2020-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201230_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_generation_code',
            field=models.TextField(default='', help_text='Make sure to follow the specifications in the README.md file!', verbose_name='Input Generation Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Summary of Question'),
        ),
    ]
