# Generated by Django 3.1.4 on 2021-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_override_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
