# Generated by Django 3.1.4 on 2020-12-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201230_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='long_description',
            field=models.TextField(help_text='Write this in the Markdown language!', max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, help_text='A short summary should suffice.', max_length=200, null=True, verbose_name='Summary of Question'),
        ),
    ]
