# Generated by Django 3.1.5 on 2021-01-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(help_text='This was automatically generated when the question is created.'),
        ),
    ]
