# Generated by Django 3.1.4 on 2021-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210124_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_players_solved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of players that solved this question'),
        ),
    ]
