# Generated by Django 3.1.4 on 2021-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20201231_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_release_datetime',
            field=models.DateTimeField(auto_now=True, help_text='When should this question be released?', verbose_name='Question Release Date-Time'),
        ),
    ]
