# Generated by Django 3.1.4 on 2021-01-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_question_release_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_release_datetime',
            field=models.DateTimeField(blank=True, help_text='When should this question be released?', verbose_name='Question Release Date-Time'),
        ),
    ]
