# Generated by Django 3.1.5 on 2021-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210126_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100, help_text='How many points is this question worth?', verbose_name='Points'),
            preserve_default=False,
        ),
    ]
