# Generated by Django 3.1.4 on 2021-01-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210101_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='override_key',
            field=models.CharField(default='Default', help_text='If the question is inaccessible, enter the full url to the question, followed by this key to access it.', max_length=10, verbose_name='Override Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_release_datetime',
            field=models.DateTimeField(help_text='When should this question be released?', verbose_name='Question Release Date-Time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
