# Generated by Django 3.1.4 on 2021-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20210102_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='override_key',
            field=models.CharField(help_text="If the question is inaccessible, enter the full url to the question, followed by 'OK=', followed by this key to access it.", max_length=10, verbose_name='Override Key'),
        ),
    ]
