# Generated by Django 3.1.4 on 2021-01-05 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20201231_1423'), ('accounts', '0003_profile_solved_puzzles'), ('accounts', '0004_remove_profile_puzzles_solved'), ('accounts', '0005_auto_20201231_2232'), ('accounts', '0006_auto_20210101_2028'), ('accounts', '0007_auto_20210101_2050'), ('accounts', '0008_profile_bio'), ('accounts', '0009_profile_theme'), ('accounts', '0010_auto_20210105_1935'), ('accounts', '0011_auto_20210105_2050')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solved_questions', models.TextField(blank=True, default='', null=True)),
                ('timeout_questions', models.TextField(blank=True, default='', null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('theme', models.CharField(choices=[('Dark Mode', 'Dark Mode'), ('Light Mode', 'Light Mode'), ('AOC', 'Advent of Code')], default='Dark Mode', max_length=50)),
            ],
        ),
    ]
