# Generated by Django 3.1.4 on 2021-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('Dark Mode', 'Dark Mode'), ('Light Mode', 'Light Mode'), ('High Contrast', 'High Contrast Mode'), ('AOC', 'Advent of Code')], default='Dark Mode', max_length=50),
        ),
    ]
