# Generated by Django 3.1.4 on 2020-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201231_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solved_puzzles',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
