# Generated by Django 3.1.4 on 2021-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210108_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='possible_new_email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('Dark Mode', 'Dark Mode'), ('Light Mode', 'Light Mode'), ('High Contrast', 'High Contrast Mode')], default='Dark Mode', max_length=50),
        ),
    ]
