# Generated by Django 3.1.4 on 2021-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210111_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
