# Generated by Django 3.1.4 on 2020-12-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_puzzles_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_puzzles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
