# Generated by Django 3.1.5 on 2021-01-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210111_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('Dark Mode', 'Dark Mode'), ('High Contrast', 'High Contrast Mode')], default='Dark Mode', max_length=50),
        ),
    ]
