# Generated by Django 3.1.4 on 2021-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('LM', 'Light Mode'), ('DM', 'Dark Mode'), ('AOC', 'Advent of Code')], default='LM', max_length=50),
        ),
    ]
