# Generated by Django 3.1.4 on 2021-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('Light Mode', 'Light Mode'), ('Dark Mode', 'Dark Mode'), ('AOC', 'Advent of Code')], default='LM', max_length=50),
        ),
    ]
