# Generated by Django 3.1.4 on 2021-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210105_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('Dark Mode', 'Dark Mode'), ('Light Mode', 'Light Mode'), ('AOC', 'Advent of Code')], default='Dark Mode', max_length=50),
        ),
    ]
